#!/bin/bash
set -e -x

#fly -t t0 login -c http://localhost:8080/
docker build -t thaniyarasu/pr . -f Dockerfile-ruby
docker push thaniyarasu/pr
echo 'y' | fly -t t0 dp -p pl1
echo 'y' | fly -t t0 sp -p pl1 -c ci/pl0.yaml --load-vars-from ci/cre.yml
fly -t t0 up -p pl1
fly -t t0 tj -j pl1/j0
fly -t t0 w -j pl1/j0
#fly -t t0 hijack -j pl1/j0 -c pl1/r0 bash
